import os
import tempfile
import time
import unittest
from pathlib import Path

from scripts.backends.base import GenerationBackendError
from scripts.backends.manual_chatgpt_backend import ManualChatGPTBackend
from scripts.models import WorkflowStep


class ManualChatGPTBackendTests(unittest.TestCase):
    def setUp(self):
        self.temp_dir = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp_dir.cleanup)
        self.output_root = Path(self.temp_dir.name) / "output"
        self.step = WorkflowStep(
            step_number=3,
            step_id="03-system-architecture",
            name="System Architecture",
            prompt_template_path="unused.md",
            output_path="02-technical/03-system-architecture.md",
        )
        self.prompts = []
        self.response_to_write: str | None = None
        self.backend = ManualChatGPTBackend(input_func=self._record_prompt)

    def test_prompt_export_path_is_correct(self):
        self.response_to_write = "# Response\n\nGenerated architecture."

        self.backend.generate(
            step=self.step,
            prompt="# Rendered Prompt\n\nBuild the architecture.",
            context={"OUTPUT_ROOT": str(self.output_root)},
        )

        expected_path = (
            self.output_root
            / "99-meta"
            / "pending-prompts"
            / "03-system-architecture.prompt.md"
        )
        self.assertTrue(expected_path.is_file())
        self.assertIn("Build the architecture", expected_path.read_text(encoding="utf-8"))

    def test_response_import_path_is_correct(self):
        expected_path = (
            self.output_root
            / "99-meta"
            / "manual-responses"
            / "03-system-architecture.response.md"
        )
        self.response_to_write = "# Manual Response\n\nGenerated."

        result = self.backend.generate(
            step=self.step,
            prompt="# Rendered Prompt",
            context={"OUTPUT_ROOT": str(self.output_root)},
        )

        self.assertEqual(result, "# Manual Response\n\nGenerated.")
        self.assertEqual(expected_path.read_text(encoding="utf-8"), result)

    def test_missing_response_file_fails_clearly(self):
        with self.assertRaises(GenerationBackendError) as error:
            self.backend.generate(
                step=self.step,
                prompt="# Rendered Prompt",
                context={"OUTPUT_ROOT": str(self.output_root)},
            )

        self.assertIn("response file was not found", str(error.exception))

    def test_empty_response_file_fails_validation(self):
        self.response_to_write = "  \n"

        with self.assertRaises(GenerationBackendError) as error:
            self.backend.generate(
                step=self.step,
                prompt="# Rendered Prompt",
                context={"OUTPUT_ROOT": str(self.output_root)},
            )

        self.assertIn("response file is empty", str(error.exception))

    def test_valid_response_content_is_returned(self):
        self.response_to_write = "# Architecture\n\nGenerated by ChatGPT."

        result = self.backend.generate(
            step=self.step,
            prompt="# Rendered Prompt",
            context={"OUTPUT_ROOT": str(self.output_root)},
        )

        self.assertEqual(result, "# Architecture\n\nGenerated by ChatGPT.")

    def test_response_missing_expected_h1_fails_validation(self):
        self.response_to_write = "# Wrong Title\n\n## Architecture Overview\n\nGenerated."

        with self.assertRaises(GenerationBackendError) as error:
            self.backend.generate(
                step=self.step,
                prompt="# Rendered Prompt",
                context={
                    "OUTPUT_ROOT": str(self.output_root),
                    "EXPECTED_H1": "System Architecture",
                },
            )

        self.assertIn("Manual ChatGPT response failed validation", str(error.exception))
        self.assertIn("expected H1", str(error.exception))

    def test_response_missing_required_section_fails_validation(self):
        step = WorkflowStep(
            step_number=3,
            step_id="03-system-architecture",
            name="System Architecture",
            prompt_template_path="unused.md",
            output_path="02-technical/03-system-architecture.md",
            required_sections=["Architecture Overview"],
        )
        self.response_to_write = "# System Architecture\n\n## Summary\n\nGenerated."

        with self.assertRaises(GenerationBackendError) as error:
            self.backend.generate(
                step=step,
                prompt="# Rendered Prompt",
                context={"OUTPUT_ROOT": str(self.output_root)},
            )

        self.assertIn("missing required sections", str(error.exception))

    def test_response_with_chat_preamble_fails_validation(self):
        self.response_to_write = (
            "Sure, here is the Markdown.\n\n# System Architecture\n\nGenerated."
        )

        with self.assertRaises(GenerationBackendError) as error:
            self.backend.generate(
                step=self.step,
                prompt="# Rendered Prompt",
                context={"OUTPUT_ROOT": str(self.output_root)},
            )

        self.assertIn("chat preamble", str(error.exception))

    def test_response_with_unresolved_placeholder_fails_validation(self):
        self.response_to_write = "# System Architecture\n\nUse {{TECH_STACK}}."

        with self.assertRaises(GenerationBackendError) as error:
            self.backend.generate(
                step=self.step,
                prompt="# Rendered Prompt",
                context={"OUTPUT_ROOT": str(self.output_root)},
            )

        self.assertIn("{{TECH_STACK}}", str(error.exception))

    def test_stale_existing_response_file_fails_clearly(self):
        response_path = self._write_response("# Old Response\n\nDo not reuse.")
        old_time = time.time() - 60
        os.utime(response_path, (old_time, old_time))

        with self.assertRaises(GenerationBackendError) as error:
            self.backend.generate(
                step=self.step,
                prompt="# New Rendered Prompt",
                context={"OUTPUT_ROOT": str(self.output_root)},
            )

        self.assertIn("older than the exported prompt", str(error.exception))

    def test_response_written_after_prompt_export_is_returned(self):
        class ResponseWritingInput:
            def __init__(self, backend, output_root, step):
                self.backend = backend
                self.output_root = output_root
                self.step = step

            def __call__(self, prompt):
                path = self.backend.response_path(self.output_root, self.step.step_id)
                path.write_text("# Fresh Response\n\nGenerated now.", encoding="utf-8")
                return ""

        backend = ManualChatGPTBackend(input_func=None)
        backend.input_func = ResponseWritingInput(backend, self.output_root, self.step)

        result = backend.generate(
            step=self.step,
            prompt="# Rendered Prompt",
            context={"OUTPUT_ROOT": str(self.output_root)},
        )

        self.assertEqual(result, "# Fresh Response\n\nGenerated now.")

    def test_backend_does_not_require_openai_api_key(self):
        original_api_key = os.environ.pop("OPENAI_API_KEY", None)
        self.addCleanup(self._restore_api_key, original_api_key)
        self.response_to_write = "# Response\n\nNo API key needed."

        result = self.backend.generate(
            step=self.step,
            prompt="# Rendered Prompt",
            context={"OUTPUT_ROOT": str(self.output_root)},
        )

        self.assertIn("No API key needed", result)

    def test_missing_output_root_fails_clearly(self):
        with self.assertRaises(GenerationBackendError) as error:
            self.backend.generate(
                step=self.step,
                prompt="# Rendered Prompt",
                context={},
            )

        self.assertIn("OUTPUT_ROOT", str(error.exception))

    def _write_response(self, content: str) -> Path:
        path = self.backend.response_path(self.output_root, self.step.step_id)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        return path

    def _record_prompt(self, prompt: str) -> str:
        self.prompts.append(prompt)
        if self.response_to_write is not None:
            self._write_response(self.response_to_write)
        return ""

    def _restore_api_key(self, value):
        if value is not None:
            os.environ["OPENAI_API_KEY"] = value


if __name__ == "__main__":
    unittest.main()
