"""Deterministic generation backend for tests and offline runs."""

from __future__ import annotations

from typing import Any

from scripts.backends.base import GenerationBackend


class MockGenerationBackend(GenerationBackend):
    """Offline backend that returns stable Markdown without credentials."""

    backend_name = "mock"
    generation_mode = "deterministic_mock"

    def generate(self, step: Any, prompt: str, context: dict[str, Any]) -> str:
        if prompt is None:
            raise ValueError("Prompt cannot be None.")

        step_id = getattr(step, "step_id", "unknown-step")
        step_name = getattr(step, "name", "Workflow Step")
        preview = _prompt_preview(prompt)
        section_blocks = "\n\n".join(
            f"## {section}\n\nDeterministic placeholder content for {section}."
            for section in _fake_required_sections(step)
        )
        return (
            "# Fake LLM Response\n\n"
            "## Summary\n\n"
            f"Deterministic Markdown generated by MockGenerationBackend for {step_name}.\n\n"
            "## Step\n\n"
            f"{step_id}\n\n"
            "## Prompt Preview\n\n"
            f"{preview}\n\n"
            f"{section_blocks}\n"
        )


def _prompt_preview(prompt: str, max_length: int = 120) -> str:
    normalized = " ".join(prompt.split()).strip()
    if not normalized:
        return "(empty prompt)"
    if len(normalized) <= max_length:
        return normalized
    return normalized[: max_length - 3] + "..."


def _fake_required_sections(step: Any) -> list[str]:
    step_sections = list(getattr(step, "required_sections", []) or [])
    if step_sections:
        return step_sections

    try:
        from scripts.workflow_steps import WORKFLOW_STEPS
    except Exception:
        return [
            "Summary",
            "Product Vision",
            "Recommended Stack",
            "Architecture Overview",
            "Primary Journey",
            "Epic Summary",
            "Story List",
            "Technical Story List",
            "Layer Overview",
            "Dependency Summary",
            "Roadmap Overview",
            "Optimized Stories",
            "Prompt Index",
            "Objective",
            "QA Strategy",
            "Documentation Goals",
        ]

    sections: list[str] = []
    for workflow_step in WORKFLOW_STEPS:
        for section in workflow_step.required_sections:
            if section not in sections:
                sections.append(section)
    return sections
