"""LLM client interfaces and test doubles."""

from __future__ import annotations

from typing import Protocol


class LLMClient(Protocol):
    def generate(self, prompt: str) -> str:
        """Generate Markdown text for a rendered prompt."""


class FakeLLMClient:
    """Deterministic LLM test double for offline workflow tests."""

    def generate(self, prompt: str) -> str:
        if prompt is None:
            raise ValueError("Prompt cannot be None.")

        preview = _prompt_preview(prompt)
        return (
            "# Fake LLM Response\n\n"
            "## Summary\n\n"
            "This is deterministic Markdown generated by FakeLLMClient.\n\n"
            "## Prompt Preview\n\n"
            f"{preview}\n"
        )


def _prompt_preview(prompt: str, max_length: int = 120) -> str:
    normalized = " ".join(prompt.split()).strip()
    if not normalized:
        return "(empty prompt)"
    if len(normalized) <= max_length:
        return normalized
    return normalized[: max_length - 3] + "..."
