"""LLM client interfaces and test doubles."""

from __future__ import annotations

import os
import time
from typing import Any, Callable
from typing import Protocol


class LLMClient(Protocol):
    def generate(self, prompt: str) -> str:
        """Generate Markdown text for a rendered prompt."""


class LLMClientError(RuntimeError):
    """Raised when an LLM provider cannot generate a usable response."""


class OpenAILLMClient:
    """OpenAI-backed LLM client using the same interface as the fake client."""

    def __init__(
        self,
        config: dict[str, Any],
        api_key: str | None = None,
        openai_client: Any | None = None,
        env_loader: Callable[[], Any] | None = None,
    ) -> None:
        self.config = config or {}
        llm_config = self.config.get("llm", {})
        self.model = llm_config.get("model", "gpt-4.1-mini")
        self.temperature = llm_config.get("temperature", 0.2)
        self.max_retries = int(llm_config.get("max_retries", 2))
        self.retry_delay_seconds = float(llm_config.get("retry_delay_seconds", 0))
        self.timeout_seconds = float(llm_config.get("timeout_seconds", 60))

        self._load_environment(env_loader)
        self.api_key = api_key or os.environ.get("OPENAI_API_KEY")
        if not self.api_key:
            raise LLMClientError(
                "OPENAI_API_KEY is not configured. Add it to your environment "
                "or local .env file, or run with --mock-llm."
            )

        self.client = openai_client or self._create_openai_client()

    def generate(self, prompt: str) -> str:
        if prompt is None:
            raise ValueError("Prompt cannot be None.")
        if not prompt.strip():
            raise ValueError("Prompt cannot be empty.")

        last_error: Exception | None = None
        attempts = self.max_retries + 1
        for attempt in range(attempts):
            try:
                response = self.client.responses.create(
                    model=self.model,
                    input=prompt,
                    temperature=self.temperature,
                    timeout=self.timeout_seconds,
                )
                text = _extract_response_text(response)
                if not text.strip():
                    raise LLMClientError("OpenAI returned an empty response.")
                return text
            except LLMClientError:
                raise
            except Exception as error:
                last_error = error
                if attempt >= self.max_retries or not _is_retryable_error(error):
                    raise LLMClientError(
                        f"OpenAI generation failed: {_safe_error_message(error)}"
                    ) from error
                if self.retry_delay_seconds > 0:
                    time.sleep(self.retry_delay_seconds)

        raise LLMClientError(
            f"OpenAI generation failed: {_safe_error_message(last_error)}"
        )

    def _load_environment(self, env_loader: Callable[[], Any] | None) -> None:
        if env_loader is not None:
            env_loader()
            return

        try:
            from dotenv import load_dotenv
        except ModuleNotFoundError:
            return

        load_dotenv()

    def _create_openai_client(self):
        try:
            from openai import OpenAI
        except ModuleNotFoundError as error:
            raise LLMClientError(
                "OpenAI SDK is not installed. Run `pip install -r requirements.txt`."
            ) from error

        return OpenAI(api_key=self.api_key, timeout=self.timeout_seconds, max_retries=0)


class FakeLLMClient:
    """Deterministic LLM test double for offline workflow tests."""

    def generate(self, prompt: str) -> str:
        if prompt is None:
            raise ValueError("Prompt cannot be None.")

        preview = _prompt_preview(prompt)
        section_blocks = "\n\n".join(
            f"## {section}\n\nDeterministic placeholder content for {section}."
            for section in _fake_required_sections()
        )
        return (
            "# Fake LLM Response\n\n"
            "## Summary\n\n"
            "This is deterministic Markdown generated by FakeLLMClient.\n\n"
            "## Prompt Preview\n\n"
            f"{preview}\n\n"
            f"{section_blocks}\n"
        )


def _prompt_preview(prompt: str, max_length: int = 120) -> str:
    normalized = " ".join(prompt.split()).strip()
    if not normalized:
        return "(empty prompt)"
    if len(normalized) <= max_length:
        return normalized
    return normalized[: max_length - 3] + "..."


def _fake_required_sections() -> list[str]:
    try:
        from scripts.workflow_steps import WORKFLOW_STEPS
    except Exception:
        return [
            "Summary",
            "Product Vision",
            "Recommended Stack",
            "Architecture Overview",
            "Primary Journey",
            "Epic Summary",
            "Story List",
            "Technical Story List",
            "Layer Overview",
            "Dependency Summary",
            "Roadmap Overview",
            "Optimized Stories",
            "Prompt Index",
            "Objective",
            "QA Strategy",
            "Documentation Goals",
        ]

    sections: list[str] = []
    for step in WORKFLOW_STEPS:
        for section in step.required_sections:
            if section not in sections:
                sections.append(section)
    return sections


def _extract_response_text(response: Any) -> str:
    output_text = getattr(response, "output_text", None)
    if output_text is not None:
        return str(output_text)

    if isinstance(response, dict):
        output_text = response.get("output_text")
        if output_text is not None:
            return str(output_text)

    raise LLMClientError("OpenAI response did not contain Markdown text.")


def _is_retryable_error(error: Exception) -> bool:
    error_name = error.__class__.__name__.lower()
    return any(
        marker in error_name
        for marker in (
            "timeout",
            "connection",
            "ratelimit",
            "rate_limit",
            "internalserver",
            "server",
            "serviceunavailable",
        )
    )


def _safe_error_message(error: Exception | None) -> str:
    if error is None:
        return "unknown provider error"
    message = str(error) or error.__class__.__name__
    api_key = os.environ.get("OPENAI_API_KEY")
    if api_key:
        message = message.replace(api_key, "[redacted]")
    return message
